pipeline {
  agent any
  
  
  tools{
    terraform "Terraform1.1.7"  
  }
  
  
  environment{
    AWS_ACCOUNT_ID = credentials('aws.id')
    AWS_ACCESS_KEY = credentials('aws.access.key')
    AWS_SECRET_KEY = credentials('aws.secret.key')
  }
  
  
  stages{
    stage('terraform-init') {
      steps {
        dir("eks"){
          sh 'ls -a'
          sh 'terraform init -backend-config=backend.hcl' 
        }
      }
    }
    stage('set-tf-vars'){
      steps{
        dir("eks"){
          sh "aws s3 cp s3://js-env-vars/input.tfvars ."
        }
      }
    }
    stage('terraform-plan') {
      steps {
        dir("eks"){
          sh 'terraform plan -var-file=input.tfvars -no-color'
        }
      }
    }
    stage('terraform-apply') {
      steps {
        dir("eks"){
          sh 'terraform apply -var-file=input.tfvars -auto-approve -no-color'
        }
      }
    }
  }
}
